# Generated by Django 4.2.7 on 2023-11-12 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledFlight',
            fields=[
                ('scheduled_flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('duration', models.CharField(max_length=10)),
                ('flight_cost', models.FloatField()),
                ('base_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_routes.baseflight')),
            ],
        ),
    ]
