# Generated by Django 4.2.7 on 2023-11-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledflight',
            name='arrival_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduledflight',
            name='arrival_time',
            field=models.TimeField(null=True),
        ),
    ]
