# Generated by Django 4.2.7 on 2023-11-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_schedule', '0002_alter_scheduledflight_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledflight',
            name='arrival_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='scheduledflight',
            name='arrival_time',
            field=models.TimeField(blank=True),
        ),
    ]
